<div id="content-header">
				<h1>Home</h1>
			</div>
			
                        <?php echo $this->breadcrumb() ?>
                       
			<div class="container-fluid">
						<div class="span4 offset3">
							<div class="row-fluid">
								<div class="btn-group ">
								  <button class="btn btn-large btn-primary">Activity Info</button>
								   <button class="btn btn-large">Contributors</button>
								  <button class="btn btn-large">Participants</button>
								  <button class="btn btn-large">Outcomes</button>
								</div>
							</div>
						</div>
						
				<div class="row-fluid">
				
					<div class="span12">
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="icon-align-justify"></i>									
								</span>
								<h5>Activity Information.</h5>
							</div>
							<div class="widget-content nopadding">
								<form action="#" method="get" class="form-horizontal">
								
									<div class="control-group">
										<label class="control-label">Activity Name :</label>
										<div class="controls form-input">
											<input type="text"  required="required"  placeholder="Please don't use short forms"/>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Type :</label>
										<div class="controls">
											<select>
												<option>Pannel Discussion</option>
												<option>Lecture/Talk</option>
												<option>Excercise/Game</option>
												<option>Confrence</option>
												<option>Competition</option>
												<option>Workshop</option>
												<option>Course</option>
												<option>Mentoring</option>
												<option>Startup Support</option>
												<option>Outreach</option>
												<option>Review Webinar</option>
												<option>National Platform</option>
											</select>
										</div>
									</div>
									
									<div class="control-group">
										<label class="control-label">Scale :</label>
										<div class="controls">
											<select>
												<option>Local</option>
												<option>National</option>
												<option>International</option>	
											</select>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Organised by :</label>
										<div class="controls">
											<select>
												<option>E-cell</option>
												<option>ESC</option>
												<option>EDC</option>
												<option>CC</option>
												<option>IEDC</option>
												<option>SVMU</option>
												<option>TBI</option>
												<option>Faculty</option>
												<option>Alumni Association</option>
												<option>NEN</option>
												<option>E club</option>
												<option>Others</option>
											</select>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Level :</label>
										<div class="controls">
											<select>
												<option>Basic</option>
												<option>Intermediate</option>
												<option>Advance</option>
											</select>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">Course Credits :</label>
										<div class="controls">
											<select>
												<option>Confrence</option>
												<option>Competition</option>
												<option>Workshop</option>
												<option>Course</option>
												<option>Mentoring</option>
												<option>Startup Support</option>
												<option>Outreach</option>
												<option>Review</option>
												<option>Webinar</option>
												<option>National Platform</option>
											</select>
										</div>
									</div>
                                   
								</form>
							</div>
						</div>
					</div>
				</div>
				
				<div class="row-fluid">
					<div class="span12">
						<div class="widget-box">
							<div class="widget-title">
								<span class="icon">
									<i class="icon-align-justify"></i>									
								</span>
								<h5>Activity Place Time</h5>
							</div>
							<div class="widget-content nopadding">
								<form action="#" method="get" class="form-horizontal">
								
									
									<div class="control-group">
										<label class="control-label">City :</label>
										<div class="controls">
											<select>
												<option>Institute City</option>
												<option>option 1</option>
												<option>option 2</option>
												<option>option 3</option>
												<option>option 4</option>
											</select>
										</div>
									</div>
									
									<div class="control-group">
										<label class="control-label">Venu :</label>
										<div class="controls">
											<select>
												<option>List of College Name</option>
												<option>National Institute of Technology</option>
												<option>Shoba Institute of Engineering</option>	
											</select>
										</div>
									</div>
									 <div class="control-group">
                                        <label class="control-label">Date picker</label>
                                        <div class="controls form-input">
                                            <input type="text" data-date="15-01-2013" data-date-format="dd-mm-yyyy" value="15-01-2013" class="datepicker" />
                                        </div>
                                    </div>
									<div class="control-group">
										<label class="control-label">Duration :</label>
										<div class="controls form-input">
											<input type="text" placeholder="No. of Days (Ex: 2)">
										</div> 
									</div>
									<div class="form-actions">
										<button type="submit" class="btn btn-primary">Save</button>
									</div>
									
                                   
								</form>
							</div>
						</div>
					</div>
				</div>
				
				<div class="row-fluid">
					<div id="footer" class="span12">
						2012 &copy; NAN Admin.
					</div>
				</div>
			</div>