<div class="row-fluid">
						<div class="row-fluid">
							<div class="span12">
								<div class="widget-box">
									<div class="widget-title">
										<span class="icon">
											<i class="icon-pencil"></i>
										</span>
										<h5>Create new activity</h5>
									</div>
									<div class="widget-content nopadding">
										<form  class="form-horizontal" name="insertactivityparticipants" action="<?php echo $_SERVER['PHP_SELF'] ?>?type=insertParticipants" method="post" >
											
													<div class="control-group">
															<div class="span9 offset2">
																<div class="row-fluid">
																	<div class="btn-group ">
																		 <button class="btn btn-large">Activity Info</button>
																		  <button class="btn btn-large">Contributors</button>
																		  <button class="btn btn-large btn-success">Participants</button>
																		  <button class="btn btn-large">Outcomes</button>
																	</div>
																</div>
															</div>
														</div>
														
														<div class="control-group">
															<label class="control-label">Activity Participants :-</label>
														</div>
														
														<div class="control-group">
															<label class="control-label">Number of Participants :</label>
																<div class="controls form-input">
																	<input type="number" name="activitybeneficiaries_number"  id="activitybeneficiaries_number"   placeholder="Count"/>
																</div>
														</div>
														
														<div class="control-group">
																<label class="control-label">Number of Participants from Institute :</label>
																	<div class="controls form-input">
																		<input type="number" name="activitybeneficiaries_institute"  id="activitybeneficiaries_institute"   placeholder="Count"/>
																	</div>
														</div>
														
													<div class="control-group">
															<label class="control-label">Total Fees Collected :</label>
																<div class="controls form-input">
																	<input type="number" name="activitybeneficiaries_fees"  id="activitybeneficiaries_fees"   placeholder="Rs: xxxx"/>
																</div>
													</div>
													<div class="control-group">
															<div class="widget-title"><span class="icon"><i class="icon-user"></i></span>
																<h5>Participant Details</h5>
															</div>
													</div>
													
													<div class="control-group">
															<div class="controls">
																	<div class="span4">
																		<input type="file" />Upload
																	</div>
																	<div class="span3 dwnd-link"><i class="icon-download-alt"></i>
																		<a href="#"> Download Template</a>
																	</div>
															</div>
													</div>				
													 <table class="table table-bordered table-striped">
														<thead>
															<tr>
																<th>Student/Entrepreneur</th>
																<th>First Name</th>
																<th>Last Name</th>
																<th>Email Id</th>
																<th>Mobile No</th>
																<th>Fees Paid</th>
																<th>Options</th>
															</tr>
														</thead>
														<tbody>
															<tr class="even">
																<td><input type="text" name="student[]" ></td>
																<td><input type="text"  name="first_name[]"></td>
																<td><input type="text" name="last_name[]" > </td>
																<td><input type="text"  name="email[]"></td>
																<td><input type="text" name="mobile[]"></td>
																<td><input type="text" name="fees_paid[]"></td>
																<td><input type="button" class="addnew btn" value="Add New Entry" /></td>
															</tr>
															
														</tbody>
													</table>	
                                                                                         
                                                                                           
										</div>
											<div class="form-actions">
                                                <input type="text" name="activity_id" value="<?php echo $this->output['activity_id'] ?>" />
													<input type="submit" class="btn btn-primary"  value="submit" />
															
											</div>
												
										</form>
									
								</div>
							</div>
						</div>
					</div>